import type { PlacarsoftGroupResponse } from "./placarsoft";

export const placarsoftGroup19Fixture = {
    status: 1,
    updated_at: "21/04/2026 18:36:48",
    current_round_id: "116",
    result: {
        id: "19",
        name: "Grupo Unico",
        table: [
            {
                id: "546701857821752638",
                name: "Roseta Cravada FC",
                shortname: "RCF",
                data: {
                    games: 3,
                    points: 6,
                    wins: 2,
                    loses: 1,
                    score_scored: 10,
                    score_conceded: 8,
                },
                uri: "/equipe/546701857821752638/roseta-cravada-fc",
                form: ["l", "w", "w"],
                shield_thumb_url: "https://placarsoft.example/roseta-thumb.jpeg",
                index: 1,
            },
            {
                id: "546701639717945199",
                name: "Veteranos PAC",
                shortname: "VPA",
                data: {
                    games: 3,
                    points: 6,
                    wins: 2,
                    loses: 1,
                    score_scored: 10,
                    score_conceded: 7,
                },
                uri: "/equipe/546701639717945199/veteranos-pac",
                form: ["w", "l", "w"],
                shield_thumb_url: "https://placarsoft.example/veteranos-thumb.jpeg",
                index: 2,
            },
            {
                id: "548440774413595047",
                name: "Real Alagoas - Sport Club Real Alagoas",
                shortname: "RAS",
                data: {
                    games: 3,
                    points: 6,
                    wins: 2,
                    loses: 1,
                    score_scored: 12,
                    score_conceded: 5,
                },
                uri: "/equipe/548440774413595047/real-alagoas-sport-club-real-alagoas",
                form: ["l", "w", "w"],
                shield_thumb_url: "https://placarsoft.example/real-alagoas-thumb.jpeg",
                index: 3,
            },
            {
                id: "546701734416939917",
                name: "Resenha FC",
                shortname: "RFC",
                data: {
                    games: 3,
                    points: 3,
                    wins: 1,
                    loses: 2,
                    score_scored: 13,
                    score_conceded: 10,
                },
                uri: "/equipe/546701734416939917/resenha-fc",
                form: ["w", "l", "l"],
                shield_thumb_url: "https://placarsoft.example/resenha-thumb.jpeg",
                index: 7,
            },
        ],
        rounds: [
            {
                id: "114",
                order: 1,
                name: "Rodada 1",
                duels: [
                    {
                        id: "550722242598876789",
                        name: "Jogo 1",
                        t1_team_id: "548440774413595047",
                        t2_team_id: "546701544469493807",
                        team_1_name: "Real Alagoas - Sport Club Real Alagoas",
                        team_1_shortname: "RAS",
                        team_1_shield_thumb_url: "https://placarsoft.example/real-alagoas-thumb.jpeg",
                        team_2_name: "Bar Sem Lona FC",
                        team_2_shortname: "BSL",
                        team_2_shield_thumb_url: "https://placarsoft.example/bar-sem-lona-thumb.jpeg",
                        starts_at_formatted: "07/04/2026 19:00",
                        result_name: "vitoria de Real Alagoas - Sport Club Real Alagoas",
                        public_uri: "/partidas/550722242598876789/jogo-1",
                        live: false,
                        done: true,
                        score_1_formatted: 6,
                        score_2_formatted: 0,
                        subscore_1_formatted: "",
                        subscore_2_formatted: "",
                        space_name: "Ginasio Municipal de Esportes Alberto Covielo - Quadra",
                    },
                ],
            },
            {
                id: "117",
                order: 2,
                name: "Rodada 4",
                duels: [
                    {
                        id: "550724666659126927",
                        name: "Jogo 13",
                        t1_team_id: "546650092409647386",
                        t2_team_id: "550605145323550678",
                        team_1_name: "Meia Boca Juniors FC",
                        team_1_shortname: "MBJ",
                        team_1_shield_thumb_url: "https://placarsoft.example/meia-boca-thumb.jpeg",
                        team_2_name: "Unidos da Vila FC",
                        team_2_shortname: "UVF",
                        team_2_shield_thumb_url: "https://placarsoft.example/unidos-vila-thumb.jpeg",
                        starts_at_formatted: "23/04/2026 19:00",
                        result_name: "indefinido",
                        public_uri: "/partidas/550724666659126927/jogo-13",
                        live: false,
                        done: false,
                        score_1_formatted: "",
                        score_2_formatted: "",
                        subscore_1_formatted: "",
                        subscore_2_formatted: "",
                        space_name: "Ginasio Municipal de Esportes Alberto Covielo - Quadra",
                    },
                ],
            },
        ],
        phase: {
            id: "28",
            name: "Fase de Grupo",
        },
        competition: {
            id: "544099817090171200",
            name: "Campeonato Municipal de Futsal",
            nickname: "Futsal 7 de Marco \"Maciel da Costa da Conceicao\"",
            common_name: "Futsal 7 de Marco \"Maciel da Costa da Conceicao\"",
            slug: "futsal-7-de-marco-maciel-da-costa-da-conceicao",
            public_uri: "/campeonatos/544099817090171200/futsal-7-de-marco-maciel-da-costa-da-conceicao",
        },
    },
    cached: false,
} as const satisfies PlacarsoftGroupResponse;
